CREATE DATABASE intelcost_bienes CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE intelcost_bienes.CITIES (
	ID INT auto_increment NOT NULL,
	NAME varchar(100) NOT NULL,
	PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE intelcost_bienes.TYPES (
	ID INT auto_increment NOT NULL,
	NAME varchar(100) NOT NULL,
	PRIMARY KEY (ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

CREATE TABLE intelcost_bienes.HOUSES (
	ID INT auto_increment NOT NULL,
	ADDRESS varchar(120) NOT NULL,
	ID_CITY INT NOT NULL,
	PHONE INT NOT NULL,
	POSTAL_CODE INT NOT NULL,
	ID_TYPE INT NOT NULL,
	PRICE INT NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_HOUSES_CITY FOREIGN KEY (ID_CITY) REFERENCES CITIES(ID),
	CONSTRAINT FK_HOUSES_TYPE FOREIGN KEY (ID_TYPE) REFERENCES TYPES(ID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_general_ci;

COMMIT;